### ISSUE TITLE
Build a habitat package on Jenkins

### ISSUE THREAD

**Issue by gscho** [Indellient/jenkins#13]
Successfully build a habitat package against the public or internal depot

**Comment by aumkarpraja** [comment]
Package builds successfully on Jenkins after making use of Skyler's plugin. @skylerto @gscho Does it need to actually appear in our builder as well as a package? Still working on that portion.

**Comment by aumkarpraja** [comment]
Blocked for today, @skylerto is using Jenkins for a demo, best to leave it untouched for today.
